#!/bin/sh

PATH=${PATH##*.opam}
PATH=${PATH#*:}

unset OPAMSWITCH

printf "<p>opamcheck launched on %s<br>" "$(date -u +"%F %T UTC")" \
  > $OPCSANDBOX/launch-info
printf "with arguments: %s</p>" "$*" >>$OPCSANDBOX/launch-info
opamcheck run "$@"
rm -rf $OPCSANDBOX/summary
while [ $# -gt 1 ]; do shift; done
opamcheck summarize -head "$(<$OPCSANDBOX/launch-info)" "$1"
